# Generated by Django 3.1.1 on 2020-09-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-timestamp']},
        ),
    ]
